feat: Allow Velero container creation
bank-vaults/vault-helm-chart pull request #26
Opened 2023-07-24 17:52 UTC by tanmay-pnaik

Allow Velero container creation without the use of CRDs

Referred to config at https://github.com/bank-vaults/vault-operator/blob/main/pkg/apis/vault/v1alpha1/vault_types.go

Took the liberty to increase the limits

2023-10-17 16:14 UTC, ramizpolic commented
Great work @tanmay-pnaik, would you mind rebasing with latest changes?
Sorry for a late reply on this, we have been working on features and fixes across other repos.

2023-11-03 09:40 UTC, tanmay-pnaik commented
> Great work @tanmay-pnaik, would you mind rebasing with latest changes? Sorry for a late reply on this, we have been working on features and fixes across other repos.

Done!

2023-11-03 20:12 UTC, akijakya commented
> > Great work @tanmay-pnaik, would you mind rebasing with latest changes? Sorry for a late reply on this, we have been working on features and fixes across other repos.
> 
> Done!

Hi @tanmay-pnaik, sorry for the inconvenience but merge commits are not allowed on feature branches, could you please remove those and rebase onto main instead? Thanks!

2023-11-04 00:40 UTC, ramizpolic commented
Can we also move the templates into a separate PR?

2023-11-09 12:31 UTC, tanmay-pnaik commented
> > > Great work @tanmay-pnaik, would you mind rebasing with latest changes? Sorry for a late reply on this, we have been working on features and fixes across other repos.
> > 
> > 
> > Done!
> 
> Hi @tanmay-pnaik, sorry for the inconvenience but merge commits are not allowed on feature branches, could you please remove those and rebase onto main instead? Thanks!

Done!

2023-11-09 12:31 UTC, tanmay-pnaik commented
> > > > Great work @tanmay-pnaik, would you mind rebasing with latest changes? Sorry for a late reply on this, we have been working on features and fixes across other repos.
> > > 
> > > 
> > > Done!
> > 
> > 
> > Hi @tanmay-pnaik, sorry for the inconvenience but merge commits are not allowed on feature branches, could you please remove those and rebase onto main instead? Thanks!
> 
> Done!



> Can we also move the templates into a separate PR?

Done, see https://github.com/bank-vaults/vault-helm-chart/pull/33

2023-11-09 14:03 UTC, ramizpolic requested changes
Thanks for the feature addition, but I do have to note something here:

I think we already have a way to enable support for Velero via:
- `.Values.podAnnotations` - we can use to inject Velero hook annotations
- `.Values.extraContainers` - we can use to add Velero container

I would suggest using these two fields to add this functionality. Therefore, rather than extending the helm chart, perhaps you could document this in the helm readme. Let me know if this would work for you.

2023-12-22 12:57 UTC, ramizpolic commented
@tanmay-pnaik If it's okay with you, we can close this one. I created https://github.com/bank-vaults/vault-helm-chart/issues/83 to track the other issue. Sorry for the hassle :(

2023-12-22 12:57 UTC, closed without merging