docs: Add issue template
bank-vaults/vault-helm-chart pull request #33
Opened 2023-08-03 05:18 UTC by tanmay-pnaik

## Overview

Add issue template

## Notes for reviewer

Copied from https://github.com/bank-vaults/vault-operator/tree/main/.github/ISSUE_TEMPLATE

2023-08-04 23:38 UTC, sagikazarmark submitted a review, later dismissed

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +labels: [bug]
```suggestion
labels: [kind/bug]
```

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +          required: true
```suggestion
          required: true
        - label: I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).
          required: true
```

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - Other (specify below)
```suggestion
```

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        # ...
```suggestion
```

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: Operator application logs (if relevant).
Bank-Vaults? Vault?

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +description: Suggest an idea for the Vault Helm Chart
```suggestion
description: Suggest an idea for the Vault Helm Chart
labels: [kind/enhancement]
```

2023-08-04 23:38 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +          required: true
```suggestion
          required: true
        - label: I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).
          required: true
```

2023-08-05 08:29 UTC, tanmay-pnaik commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: Operator application logs (if relevant).
Changed to Vault. :+1:

2023-10-17 16:10 UTC, ramizpolic approved these changes

2023-11-09 14:13 UTC, ramizpolic commented
@tanmay-pnaik could you do a rebase? I can merge it right away 😄

2023-11-14 16:36 UTC, ramizpolic requested changes
Git history seems to be corrupted, would you mind fixing/opening a new PR with selected changes only? Sorry for being a pain 😢

2023-11-18 15:05 UTC, tanmay-pnaik commented
> Git history seems to be corrupted, would you mind fixing/opening a new PR with selected changes only? Sorry for being a pain 😢

No worries, sorry from my end too. Resolved now.

2023-11-18 16:30 UTC, ramizpolic approved these changes

2023-11-18 16:32 UTC, merged